name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      mongo:
        image: mongo:latest
        ports:
          - 27017:27017

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    # Установка и тестирование бэкенда
    - name: Set up Node.js for Backend
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies for Backend
      working-directory: ./backend
      run: npm install

    - name: Run tests for Backend
      working-directory: ./backend
      run: npm test

    # Установка и тестирование фронтенда
    - name: Set up Node.js for Frontend
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies for Frontend
      working-directory: ./frontend
      run: npm install

    - name: Run tests for Frontend
      working-directory: ./frontend
      run: npm test
